"use client";

import { Geist, Inter, Poppins } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from '@/components/theme-provider';
import { ModeToggle } from '@/components/ModeToggle';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Provider } from 'react-redux';
import store from '@/redux/store';

const geist = Geist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
});

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en" suppressHydrationWarning>
        <head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
        </head>
        <body className={`${geist.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <ModeToggle />
            <ScrollArea className="h-screen">
              {children}
            </ScrollArea>
          </ThemeProvider>
        </body>
      </html>
    </Provider>
  );
}
